In [1]:
import numpy as np

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

In [14]:
E1 = np.array([[2, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1]])
B @ E1

array([[ 2,  2,  3,  4],
       [10,  6,  7,  8],
       [18, 10, 11, 12],
       [26, 14, 15, 16]])

In [3]:
E2 = np.array([[1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 0.5, 0],
               [0, 0, 0, 1]])
E2 @ B @ E1

array([[ 2. ,  2. ,  3. ,  4. ],
       [10. ,  6. ,  7. ,  8. ],
       [ 9. ,  5. ,  5.5,  6. ],
       [26. , 14. , 15. , 16. ]])

In [4]:
E3 = np.array([[1, 0, 0, 0],
               [0, 1, 0, 0],    
               [0, 0, 1, 0],
               [1, 0, 0, 1]])
E3 @ E2 @ B @ E1

array([[ 2. ,  2. ,  3. ,  4. ],
       [10. ,  6. ,  7. ,  8. ],
       [ 9. ,  5. ,  5.5,  6. ],
       [28. , 16. , 18. , 20. ]])

In [5]:
E4 = np.array([[1, 0, 0, 0],
              [0, 0, 1, 0],
              [0, 1, 0, 0],
              [0, 0, 0, 1]])
E3 @ E2 @ B @ E1 @ E4

array([[ 2. ,  3. ,  2. ,  4. ],
       [10. ,  7. ,  6. ,  8. ],
       [ 9. ,  5.5,  5. ,  6. ],
       [28. , 18. , 16. , 20. ]])

In [7]:
E5 = np.array([[1, -1, 0, 0],
              [0, 1, 0, 0],
              [0, -1, 1, 0],
              [0, -1, 0, 1]])
E5 @ E3 @ E2 @ B @ E1 @ E4

array([[-8. , -4. , -4. , -4. ],
       [10. ,  7. ,  6. ,  8. ],
       [-1. , -1.5, -1. , -2. ],
       [18. , 11. , 10. , 12. ]])

In [9]:
E6 = np.array([[1, 0, 0, 1],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 0]])
E5 @ E3 @ E2 @ B @ E1 @ E4 @ E6

array([[-8. , -4. , -4. , -8. ],
       [10. ,  7. ,  6. , 10. ],
       [-1. , -1.5, -1. , -1. ],
       [18. , 11. , 10. , 18. ]])

In [10]:
E7 = np.array([[1, 0, 0],
              [0, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])
E5 @ E3 @ E2 @ B @ E1 @ E4 @ E6 @ E7

array([[-8., -4., -8.],
       [10.,  6., 10.],
       [-1., -1., -1.],
       [18., 10., 18.]])

In [11]:
E5 @ E3 @ E2

array([[ 1. , -1. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ],
       [ 0. , -1. ,  0.5,  0. ],
       [ 1. , -1. ,  0. ,  1. ]])

In [12]:
E1 @ E4 @ E6 @ E7

array([[2, 0, 2],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])