In [1]:
import numpy as np

B = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12],
              [13, 14, 15, 16]])

In [2]:
E1 = np.array([[2, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 1, 0],
               [0, 0, 0, 1]])
B @ E1

array([[ 2,  2,  3,  4],
       [10,  6,  7,  8],
       [18, 10, 11, 12],
       [26, 14, 15, 16]])

In [3]:
E2 = np.array([[1, 0, 0, 0],
               [0, 1, 0, 0],
               [0, 0, 0.5, 0],
               [0, 0, 0, 1]])
E2 @ B @ E1

array([[ 2. ,  2. ,  3. ,  4. ],
       [10. ,  6. ,  7. ,  8. ],
       [ 9. ,  5. ,  5.5,  6. ],
       [26. , 14. , 15. , 16. ]])

In [4]:
E3 = np.array([[1, 0, 0, 0],
               [0, 1, 0, 0],    
               [0, 0, 1, 0],
               [1, 0, 0, 1]])
E3 @ E2 @ B @ E1

array([[ 2. ,  2. ,  3. ,  4. ],
       [10. ,  6. ,  7. ,  8. ],
       [ 9. ,  5. ,  5.5,  6. ],
       [28. , 16. , 18. , 20. ]])

In [5]:
E4 = np.array([[1, 0, 0, 0],
              [0, 0, 1, 0],
              [0, 1, 0, 0],
              [0, 0, 0, 1]])
E3 @ E2 @ B @ E1 @ E4

array([[ 2. ,  3. ,  2. ,  4. ],
       [10. ,  7. ,  6. ,  8. ],
       [ 9. ,  5.5,  5. ,  6. ],
       [28. , 18. , 16. , 20. ]])

In [6]:
E5 = np.array([[1, -1, 0, 0],
              [0, 1, 0, 0],
              [0, -1, 1, 0],
              [0, -1, 0, 1]])
E5 @ E3 @ E2 @ B @ E1 @ E4

array([[-8. , -4. , -4. , -4. ],
       [10. ,  7. ,  6. ,  8. ],
       [-1. , -1.5, -1. , -2. ],
       [18. , 11. , 10. , 12. ]])

In [7]:
E6 = np.array([[1, 0, 0, 1],
              [0, 1, 0, 0],
              [0, 0, 1, 0],
              [0, 0, 0, 0]])
E5 @ E3 @ E2 @ B @ E1 @ E4 @ E6

array([[-8. , -4. , -4. , -8. ],
       [10. ,  7. ,  6. , 10. ],
       [-1. , -1.5, -1. , -1. ],
       [18. , 11. , 10. , 18. ]])

In [8]:
E7 = np.array([[1, 0, 0],
              [0, 0, 0],
              [0, 1, 0],
              [0, 0, 1]])
E5 @ E3 @ E2 @ B @ E1 @ E4 @ E6 @ E7

array([[-8., -4., -8.],
       [10.,  6., 10.],
       [-1., -1., -1.],
       [18., 10., 18.]])

In [9]:
A = E5 @ E3 @ E2
A

array([[ 1. , -1. ,  0. ,  0. ],
       [ 0. ,  1. ,  0. ,  0. ],
       [ 0. , -1. ,  0.5,  0. ],
       [ 1. , -1. ,  0. ,  1. ]])

In [10]:
C = E1 @ E4 @ E6 @ E7
C

array([[2, 0, 2],
       [0, 1, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [11]:
A @ B @ C

array([[-8., -4., -8.],
       [10.,  6., 10.],
       [-1., -1., -1.],
       [18., 10., 18.]])

In [69]:
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])
A = np.array([[1, 2, 3],
              [2, 4, 6]])
B = np.array([[7, 8],
              [9, 10],
              [11, 12]])
C = np.array([[1, 0, 0],
              [0, 0, 1]])
beta_1 = 4
beta_2 = 5

In [70]:
a + b

array([ 3,  7, 11])

In [71]:
beta_1 * a

array([ 4, 12, 20])

In [72]:
a * b

array([ 2, 12, 30])

In [73]:
beta_1 * a + beta_2 * b

array([14, 32, 50])

In [48]:
beta_1 * A

array([[ 4,  8, 12],
       [ 8, 16, 24]])

In [19]:
A + B

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [20]:
A + C

array([[2, 2, 3],
       [2, 4, 7]])

In [21]:
(A @ B).T

array([[ 58, 116],
       [ 64, 128]])

In [22]:
B.T @ A.T

array([[ 58, 116],
       [ 64, 128]])

In [23]:
(A.T).T

array([[1, 2, 3],
       [2, 4, 6]])

In [24]:
(A + C).T

array([[2, 2],
       [2, 4],
       [3, 7]])

In [74]:
def inner_outer(a, b, mult=1):
    print(mult * np.inner(a, b))
    print(mult * np.outer(a, b))

inner_outer(a, b)
inner_outer(b, a)
inner_outer(a, a)
inner_outer(b, b)
inner_outer(a, b, beta_1)
inner_outer(beta_1 * a, b)

44
[[ 2  4  6]
 [ 6 12 18]
 [10 20 30]]
44
[[ 2  6 10]
 [ 4 12 20]
 [ 6 18 30]]
35
[[ 1  3  5]
 [ 3  9 15]
 [ 5 15 25]]
56
[[ 4  8 12]
 [ 8 16 24]
 [12 24 36]]
176
[[  8  16  24]
 [ 24  48  72]
 [ 40  80 120]]
176
[[  8  16  24]
 [ 24  48  72]
 [ 40  80 120]]


In [79]:
np.inner(b.reshape(3, 1), a.reshape(3, 1).T)

ValueError: shapes (3,1) and (3,1) not aligned: 1 (dim 1) != 3 (dim 0)

In [83]:
b.reshape(3, 1).T @ a.reshape(3, 1).T

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 1 is different from 3)