In [1]:
import numpy as np

In [4]:
def svd(A):
    u, s, vh = np.linalg.svd(A)
    print("U matrix:\n", u)
    print("Singular values:\n", s)
    print("V^T matrix:\n", vh)

In [5]:
a = np.array([[5, 0], [0, 2]])
b = np.array([[2, 0], [0, 5]])
c = np.array([[0, 3], [0, 0], [0, 0]])
d = np.array([[1, 0], [1, 0]])
e = np.array([[2 ,2], [3, 2]])

print("(a):")
svd(a)
print("\n(b):")
svd(b)
print("\n(c):")
svd(c)
print("\n(d):")
svd(d)
print("\n(e):")
svd(e)

(a):
U matrix:
 [[1. 0.]
 [0. 1.]]
Singular values:
 [5. 2.]
V^T matrix:
 [[1. 0.]
 [0. 1.]]

(b):
U matrix:
 [[0. 1.]
 [1. 0.]]
Singular values:
 [5. 2.]
V^T matrix:
 [[0. 1.]
 [1. 0.]]

(c):
U matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Singular values:
 [3. 0.]
V^T matrix:
 [[ 0.  1.]
 [-1.  0.]]

(d):
U matrix:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
Singular values:
 [1.41421356 0.        ]
V^T matrix:
 [[-1. -0.]
 [ 0.  1.]]

(e):
U matrix:
 [[-0.61541221 -0.78820544]
 [-0.78820544  0.61541221]]
Singular values:
 [4.56155281 0.43844719]
V^T matrix:
 [[-0.78820544 -0.61541221]
 [ 0.61541221 -0.78820544]]


In [7]:
A = np.array([[-5, 3], [-6, 6]])
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:\n", eigenvalues)
print("Eigenvectors:\n", eigenvectors)
print(1/np.sqrt(10), 3/np.sqrt(10))
print(2/np.sqrt(13), 3/np.sqrt(13))

Eigenvalues:
 [-3.  4.]
Eigenvectors:
 [[-0.83205029 -0.31622777]
 [-0.5547002  -0.9486833 ]]
0.31622776601683794 0.9486832980505138
0.5547001962252291 0.8320502943378437
